#!/bin/bash
set -euxo pipefail

#
# This script runs when the platform check the challenge.
#
# The platform determines if the script was successful using the exit code of this
# script. If the exit code is not 0, the script fails. 
#


if (! yq -e eval '.orbs.go == "circleci/go@1.9.0"' ~/project/.circleci/config.yml > /dev/null 2>&1); then
  fail-message "The 'orbs' configuration for 'go: circleci/go@1.9.0' must be included."
fi

if (! yq -e eval '.jobs."install-dependencies".executor.name == "go/default" and .jobs."install-dependencies".executor.tag == "1.21"' ~/project/.circleci/config.yml > /dev/null 2>&1); then
  fail-message "The 'install-dependencies' job must use the specified executor configuration."
fi

if (yq -e eval '.jobs."install-dependencies".steps[] | select(.restore_cache or .save_cache)' ~/project/.circleci/config.yml > /dev/null 2>&1); then
  fail-message "The 'install-dependencies' job must not contain 'restore_cache' or 'save_cache' keys. Please replace them with your simplified YAML utilizing the go orb."
fi

if ! grep -qE '^\s*- go/mod-download-cached' ~/project/.circleci/config.yml; then
  fail-message "The 'go/mod-download-cached' step is missing under the 'install-dependencies' job."
fi

if (yq -e eval '.jobs.test.docker[] | select(.image == "cimg/go:1.21" or .image == "cimg/postgres:15.1")' ~/project/.circleci/config.yml > /dev/null 2>&1); then
  fail-message "The 'test' job must be reconfigured to use the simplified executor config utilizing the go orb. Please remove the postgres convenience image at this time."
fi

if (! yq -e eval '.jobs.test.executor.name == "go/default" and .jobs.test.executor.tag == "1.21"' ~/project/.circleci/config.yml > /dev/null 2>&1); then
  fail-message "The 'test' job must use the specified executor configuration utilizing the go orb default executor."
fi

if (yq -e eval '.jobs."test-split-by-filename".docker[] | select(.image == "cimg/go:1.21" or .image == "cimg/postgres:15.1")' ~/project/.circleci/config.yml > /dev/null 2>&1); then
  fail-message "The 'test-split-by-filename' job must be reconfigured to use the simplified executor config utilizing the go orb."
fi

if (! yq -e eval '.jobs."test-split-by-filename".executor.name == "go/default" and .jobs."test-split-by-filename".executor.tag == "1.21"' ~/project/.circleci/config.yml > /dev/null 2>&1); then
  fail-message "The 'test-split-by-filename' job must use the specified executor configuration utilizing the go orb default executor."
fi

if (yq -e eval '.jobs."test-split-by-testname".docker[] | select(.image == "cimg/go:1.21" or .image == "cimg/postgres:15.1")' ~/project/.circleci/config.yml > /dev/null 2>&1); then
  fail-message "The 'test-split-by-testname' job must be reconfigured to use the simplified executor config utilizing the go orb."
fi

if (! yq -e eval '.jobs."test-split-by-testname".executor.name == "go/default" and .jobs."test-split-by-testname".executor.tag == "1.21"' ~/project/.circleci/config.yml > /dev/null 2>&1); then
  fail-message "The 'test-split-by-testname' job must use the specified executor configuration utilizing the go orb default executor."
fi

if (! circleci --skip-update-check config validate ~/project/.circleci/config.yml); then 
  fail-message "Uh oh - your config file isn't valid. Try running 'circleci config validate ~/project/.circleci/config.yml' in the shell to learn more."
fi
